// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MCalendar struct {
	ID                int64            `db:"id" json:"id"`
	DisplayName       string           `db:"display_name" json:"displayName"`
	BindUser          bool             `db:"bind_user" json:"bindUser"`
	OwnerUserID       pgtype.Int8      `db:"owner_user_id" json:"ownerUserId"`
	IsDeletable       bool             `db:"is_deletable" json:"isDeletable"`
	IsVisible         bool             `db:"is_visible" json:"isVisible"`
	IsReserveCalendar bool             `db:"is_reserve_calendar" json:"isReserveCalendar"`
	BackgroundColor   string           `db:"background_color" json:"backgroundColor"`
	ForegroundColor   string           `db:"foreground_color" json:"foregroundColor"`
	ViewOrder         int64            `db:"view_order" json:"viewOrder"`
	IsDeleted         bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy         int64            `db:"created_by" json:"createdBy"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy         int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MFrame struct {
	ID               int64            `db:"id" json:"id"`
	PrayDate         pgtype.Date      `db:"pray_date" json:"prayDate"`
	TargetHour       int32            `db:"target_hour" json:"targetHour"`
	StartTime        pgtype.Timestamp `db:"start_time" json:"startTime"`
	ClosingTime      pgtype.Timestamp `db:"closing_time" json:"closingTime"`
	GroupCount       int32            `db:"group_count" json:"groupCount"`
	GroupPeopleCount int32            `db:"group_people_count" json:"groupPeopleCount"`
	TotalPeopleCount int32            `db:"total_people_count" json:"totalPeopleCount"`
	UnitMinute       int32            `db:"unit_minute" json:"unitMinute"`
	ViewOrder        int64            `db:"view_order" json:"viewOrder"`
	IsDeleted        bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy        int64            `db:"created_by" json:"createdBy"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy        int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MFrameDetail struct {
	ID                  int64            `db:"id" json:"id"`
	FrameID             int64            `db:"frame_id" json:"frameId"`
	PrayDate            pgtype.Date      `db:"pray_date" json:"prayDate"`
	TargetHour          int32            `db:"target_hour" json:"targetHour"`
	StartTime           pgtype.Timestamp `db:"start_time" json:"startTime"`
	ClosingTime         pgtype.Timestamp `db:"closing_time" json:"closingTime"`
	GroupCount          int32            `db:"group_count" json:"groupCount"`
	GroupPeopleCount    int32            `db:"group_people_count" json:"groupPeopleCount"`
	TotalPeopleCount    int32            `db:"total_people_count" json:"totalPeopleCount"`
	IsClosed            bool             `db:"is_closed" json:"isClosed"`
	CloseReason         string           `db:"close_reason" json:"closeReason"`
	ViewOrder           int64            `db:"view_order" json:"viewOrder"`
	IsDeleted           bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy           int64            `db:"created_by" json:"createdBy"`
	CreatedAt           pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy           int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
	IsNotDecideDatetime bool             `db:"is_not_decide_datetime" json:"isNotDecideDatetime"`
}

type MFrameDetailsWish struct {
	ID           int64 `db:"id" json:"id"`
	FrameDetails int64 `db:"frame_details" json:"frameDetails"`
	WishesID     int64 `db:"wishes_id" json:"wishesId"`
}

type MFrameRelease struct {
	PrayDate         pgtype.Timestamp `db:"pray_date" json:"prayDate"`
	OpeningTimestamp pgtype.Timestamp `db:"opening_timestamp" json:"openingTimestamp"`
	ClosingTimestamp pgtype.Timestamp `db:"closing_timestamp" json:"closingTimestamp"`
}

type MMailTemplate struct {
	ID                    int64            `db:"id" json:"id"`
	PrayCategoryID        int64            `db:"pray_category_id" json:"prayCategoryId"`
	ProcessClassification int32            `db:"process_classification" json:"processClassification"`
	MailSubject           string           `db:"mail_subject" json:"mailSubject"`
	MailBody              string           `db:"mail_body" json:"mailBody"`
	IsActive              bool             `db:"is_active" json:"isActive"`
	ViewOrder             int64            `db:"view_order" json:"viewOrder"`
	IsDeleted             bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy             int64            `db:"created_by" json:"createdBy"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy             int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MMailTemplatePlaceholder struct {
	ID                 int64  `db:"id" json:"id"`
	PrayCategoryID     int64  `db:"pray_category_id" json:"prayCategoryId"`
	PlaceholderDisplay string `db:"placeholder_display" json:"placeholderDisplay"`
	FieldName          string `db:"field_name" json:"fieldName"`
	Formatter          string `db:"formatter" json:"formatter"`
	ViewOrder          int64  `db:"view_order" json:"viewOrder"`
}

type MPrayCategory struct {
	ID          int64            `db:"id" json:"id"`
	Title       string           `db:"title" json:"title"`
	Description string           `db:"description" json:"description"`
	IsCorprate  bool             `db:"is_corprate" json:"isCorprate"`
	ViewOrder   int64            `db:"view_order" json:"viewOrder"`
	IsDeleted   bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy   int64            `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy   int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MRole struct {
	ID        int64            `db:"id" json:"id"`
	RoleName  string           `db:"role_name" json:"roleName"`
	ViewOrder int64            `db:"view_order" json:"viewOrder"`
	IsDeleted bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy int64            `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MUser struct {
	ID             int64            `db:"id" json:"id"`
	RoleID         int64            `db:"role_id" json:"roleId"`
	AuthKey        string           `db:"auth_key" json:"authKey"`
	LoginID        string           `db:"login_id" json:"loginId"`
	PasswordHash   string           `db:"password_hash" json:"passwordHash"`
	Username       string           `db:"username" json:"username"`
	Mailaddress    string           `db:"mailaddress" json:"mailaddress"`
	AuthorityLevel int32            `db:"authority_level" json:"authorityLevel"`
	LastLogedinAt  pgtype.Timestamp `db:"last_logedin_at" json:"lastLogedinAt"`
	ViewOrder      int64            `db:"view_order" json:"viewOrder"`
	IsDeleted      bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy      int64            `db:"created_by" json:"createdBy"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy      int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWish struct {
	ID                int64            `db:"id" json:"id"`
	PrayCategoryID    int64            `db:"pray_category_id" json:"prayCategoryId"`
	WishName          string           `db:"wish_name" json:"wishName"`
	Description       string           `db:"description" json:"description"`
	IsDateDesignation bool             `db:"is_date_designation" json:"isDateDesignation"`
	IsManualInput     bool             `db:"is_manual_input" json:"isManualInput"`
	ViewOrder         int64            `db:"view_order" json:"viewOrder"`
	IsDeleted         bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy         int64            `db:"created_by" json:"createdBy"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy         int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWishesFee struct {
	ID        int64            `db:"id" json:"id"`
	WishesID  int64            `db:"wishes_id" json:"wishesId"`
	Fee       int64            `db:"fee" json:"fee"`
	ViewOrder int64            `db:"view_order" json:"viewOrder"`
	IsDeleted bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy int64            `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWishesOption struct {
	ID          int64            `db:"id" json:"id"`
	WishesID    int64            `db:"wishes_id" json:"wishesId"`
	ContentID   string           `db:"content_id" json:"contentId"`
	IsVisible   bool             `db:"is_visible" json:"isVisible"`
	Description string           `db:"description" json:"description"`
	ViewOrder   int64            `db:"view_order" json:"viewOrder"`
	IsDeleted   bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy   int64            `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy   int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWishesText struct {
	ID          int64            `db:"id" json:"id"`
	WishesID    int64            `db:"wishes_id" json:"wishesId"`
	ContentID   string           `db:"content_id" json:"contentId"`
	FieldKind   int32            `db:"field_kind" json:"fieldKind"`
	DisplayText string           `db:"display_text" json:"displayText"`
	ViewOrder   int64            `db:"view_order" json:"viewOrder"`
	IsDeleted   bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy   int64            `db:"created_by" json:"createdBy"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy   int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWishesWritingContent struct {
	ID               int64            `db:"id" json:"id"`
	WishesID         int64            `db:"wishes_id" json:"wishesId"`
	WritingContentID int64            `db:"writing_content_id" json:"writingContentId"`
	ViewOrder        int64            `db:"view_order" json:"viewOrder"`
	IsDeleted        bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy        int64            `db:"created_by" json:"createdBy"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy        int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type MWritingContent struct {
	ID        int64            `db:"id" json:"id"`
	Title     string           `db:"title" json:"title"`
	ViewOrder int64            `db:"view_order" json:"viewOrder"`
	IsDeleted bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy int64            `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type SysConnectenSetting struct {
	Key         string         `db:"key" json:"key"`
	DataType    int32          `db:"data_type" json:"dataType"`
	DataString  pgtype.Text    `db:"data_string" json:"dataString"`
	DataLong    pgtype.Int8    `db:"data_long" json:"dataLong"`
	DataDecimal pgtype.Numeric `db:"data_decimal" json:"dataDecimal"`
	DataBoolean pgtype.Bool    `db:"data_boolean" json:"dataBoolean"`
	Description pgtype.Text    `db:"description" json:"description"`
}

type TBulletinBoard struct {
	ID        int64            `db:"id" json:"id"`
	Content   string           `db:"content" json:"content"`
	IsDeleted bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy int64            `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
}

type TCalendarPlan struct {
	ID             int64            `db:"id" json:"id"`
	CalendarID     int64            `db:"calendar_id" json:"calendarId"`
	Title          string           `db:"title" json:"title"`
	StartTimestamp pgtype.Timestamp `db:"start_timestamp" json:"startTimestamp"`
	EndTimestamp   pgtype.Timestamp `db:"end_timestamp" json:"endTimestamp"`
	IsAllDay       bool             `db:"is_all_day" json:"isAllDay"`
	PlanAddress    string           `db:"plan_address" json:"planAddress"`
	Descriptions   string           `db:"descriptions" json:"descriptions"`
	OwnerID        int64            `db:"owner_id" json:"ownerId"`
	IsPrivate      bool             `db:"is_private" json:"isPrivate"`
	IsDeleted      bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy      int64            `db:"created_by" json:"createdBy"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy      int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TFudaSize struct {
	ReserveID int64 `db:"reserve_id" json:"reserveId"`
	SizeXl    int32 `db:"size_xl" json:"sizeXl"`
	SizeLg    int32 `db:"size_lg" json:"sizeLg"`
	SizeMd    int32 `db:"size_md" json:"sizeMd"`
	SizeSm    int32 `db:"size_sm" json:"sizeSm"`
	SizeXs    int32 `db:"size_xs" json:"sizeXs"`
	SizeCar   int32 `db:"size_car" json:"sizeCar"`
}

type TMailHistory struct {
	ID          int64            `db:"id" json:"id"`
	ReserveID   int64            `db:"reserve_id" json:"reserveId"`
	Subject     string           `db:"subject" json:"subject"`
	Body        string           `db:"body" json:"body"`
	IsSent      bool             `db:"is_sent" json:"isSent"`
	IsDraft     bool             `db:"is_draft" json:"isDraft"`
	SentBy      int64            `db:"sent_by" json:"sentBy"`
	SentAt      pgtype.Timestamp `db:"sent_at" json:"sentAt"`
	LastSavedAt pgtype.Timestamp `db:"last_saved_at" json:"lastSavedAt"`
}

type TPrayBasic struct {
	ReserveID            int64            `db:"reserve_id" json:"reserveId"`
	MainWishID           int64            `db:"main_wish_id" json:"mainWishId"`
	MainWishName         string           `db:"main_wish_name" json:"mainWishName"`
	SubWishID            pgtype.Int8      `db:"sub_wish_id" json:"subWishId"`
	SubWishName          string           `db:"sub_wish_name" json:"subWishName"`
	PostCode             string           `db:"post_code" json:"postCode"`
	Address1             string           `db:"address1" json:"address1"`
	Address2             string           `db:"address2" json:"address2"`
	Address3             string           `db:"address3" json:"address3"`
	Address1Kana         string           `db:"address1_kana" json:"address1Kana"`
	Address2Kana         string           `db:"address2_kana" json:"address2Kana"`
	Address3Kana         string           `db:"address3_kana" json:"address3Kana"`
	ReceiptAddressee     string           `db:"receipt_addressee" json:"receiptAddressee"`
	PrayFee              int64            `db:"pray_fee" json:"prayFee"`
	Remarks              string           `db:"remarks" json:"remarks"`
	SlipRemarks          string           `db:"slip_remarks" json:"slipRemarks"`
	IsDeleted            bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy            int64            `db:"created_by" json:"createdBy"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy            int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
	DisableReceipt       bool             `db:"disable_receipt" json:"disableReceipt"`
	ReceiptSummaryAmount int64            `db:"receipt_summary_amount" json:"receiptSummaryAmount"`
}

type TPrayCategoryAccomplishment struct {
	ReserveID             int64            `db:"reserve_id" json:"reserveId"`
	FirstAspirations      string           `db:"first_aspirations" json:"firstAspirations"`
	FirstAspirationsKana  string           `db:"first_aspirations_kana" json:"firstAspirationsKana"`
	FirstAspirationsDate  pgtype.Date      `db:"first_aspirations_date" json:"firstAspirationsDate"`
	SecondAspirations     string           `db:"second_aspirations" json:"secondAspirations"`
	SecondAspirationsKana string           `db:"second_aspirations_kana" json:"secondAspirationsKana"`
	SecondAspirationsDate pgtype.Date      `db:"second_aspirations_date" json:"secondAspirationsDate"`
	ThirdAspirations      string           `db:"third_aspirations" json:"thirdAspirations"`
	ThirdAspirationsKana  string           `db:"third_aspirations_kana" json:"thirdAspirationsKana"`
	ThirdAspirationsDate  pgtype.Date      `db:"third_aspirations_date" json:"thirdAspirationsDate"`
	IsDeleted             bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy             int64            `db:"created_by" json:"createdBy"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy             int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayCategoryChild struct {
	ReserveID      int64            `db:"reserve_id" json:"reserveId"`
	FatherName     string           `db:"father_name" json:"fatherName"`
	FatherNameKana string           `db:"father_name_kana" json:"fatherNameKana"`
	MotherName     string           `db:"mother_name" json:"motherName"`
	MotherNameKana string           `db:"mother_name_kana" json:"motherNameKana"`
	ChildrenCount  int32            `db:"children_count" json:"childrenCount"`
	IsDeleted      bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy      int64            `db:"created_by" json:"createdBy"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy      int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayCategoryCorporate struct {
	ReserveID     int64            `db:"reserve_id" json:"reserveId"`
	SafetyContent string           `db:"safety_content" json:"safetyContent"`
	SafetyPeriod  string           `db:"safety_period" json:"safetyPeriod"`
	IsDeleted     bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy     int64            `db:"created_by" json:"createdBy"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy     int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayCategoryCouple struct {
	ReserveID           int64            `db:"reserve_id" json:"reserveId"`
	ExpectedDateOfBirth string           `db:"expected_date_of_birth" json:"expectedDateOfBirth"`
	IsDeleted           bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy           int64            `db:"created_by" json:"createdBy"`
	CreatedAt           pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy           int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt           pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
	BellyBandDiv        int64            `db:"belly_band_div" json:"bellyBandDiv"`
}

type TPrayCategoryPersonal struct {
	ReserveID int64            `db:"reserve_id" json:"reserveId"`
	IsDeleted bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy int64            `db:"created_by" json:"createdBy"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayCategorySafety struct {
	ReserveID     int64            `db:"reserve_id" json:"reserveId"`
	SafetyContent string           `db:"safety_content" json:"safetyContent"`
	SafetyPeriod  string           `db:"safety_period" json:"safetyPeriod"`
	IsDeleted     bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy     int64            `db:"created_by" json:"createdBy"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy     int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayWritingContent struct {
	ID               int64 `db:"id" json:"id"`
	ReserveID        int64 `db:"reserve_id" json:"reserveId"`
	WritingContentID int64 `db:"writing_content_id" json:"writingContentId"`
}

type TPrayerCorprate struct {
	ID                          int64            `db:"id" json:"id"`
	ReserveID                   int64            `db:"reserve_id" json:"reserveId"`
	CompanyName                 string           `db:"company_name" json:"companyName"`
	CompanyNameKana             string           `db:"company_name_kana" json:"companyNameKana"`
	BranchAndDepartmentName     string           `db:"branch_and_department_name" json:"branchAndDepartmentName"`
	BranchAndDepartmentNameKana string           `db:"branch_and_department_name_kana" json:"branchAndDepartmentNameKana"`
	RepresentativeJobTitle      string           `db:"representative_job_title" json:"representativeJobTitle"`
	RepresentativeJobTitleKana  string           `db:"representative_job_title_kana" json:"representativeJobTitleKana"`
	RepresentativeName          string           `db:"representative_name" json:"representativeName"`
	RepresentativeNameKana      string           `db:"representative_name_kana" json:"representativeNameKana"`
	IsDeleted                   bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy                   int64            `db:"created_by" json:"createdBy"`
	CreatedAt                   pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy                   int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt                   pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TPrayerPersonal struct {
	ID             int64            `db:"id" json:"id"`
	ReserveID      int64            `db:"reserve_id" json:"reserveId"`
	PrayerName     string           `db:"prayer_name" json:"prayerName"`
	PrayerNameKana string           `db:"prayer_name_kana" json:"prayerNameKana"`
	Gender         int32            `db:"gender" json:"gender"`
	Birthday       pgtype.Date      `db:"birthday" json:"birthday"`
	Attribute      int64            `db:"attribute" json:"attribute"`
	PrayFee        int64            `db:"pray_fee" json:"prayFee"`
	IsDeleted      bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy      int64            `db:"created_by" json:"createdBy"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy      int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
}

type TReserve struct {
	ID                    int64            `db:"id" json:"id"`
	FrameDetailsID        int64            `db:"frame_details_id" json:"frameDetailsId"`
	PrayCategoryID        int64            `db:"pray_category_id" json:"prayCategoryId"`
	PrayDate              pgtype.Date      `db:"pray_date" json:"prayDate"`
	ApplicantName         string           `db:"applicant_name" json:"applicantName"`
	ApplicantEmailAddress string           `db:"applicant_email_address" json:"applicantEmailAddress"`
	ApplicantTelNo        string           `db:"applicant_tel_no" json:"applicantTelNo"`
	ParticipantsNumber    int32            `db:"participants_number" json:"participantsNumber"`
	Memo                  string           `db:"memo" json:"memo"`
	ReservationKey        string           `db:"reservation_key" json:"reservationKey"`
	IsDeleted             bool             `db:"is_deleted" json:"isDeleted"`
	CreatedBy             int64            `db:"created_by" json:"createdBy"`
	CreatedAt             pgtype.Timestamp `db:"created_at" json:"createdAt"`
	UpdatedBy             int64            `db:"updated_by" json:"updatedBy"`
	UpdatedAt             pgtype.Timestamp `db:"updated_at" json:"updatedAt"`
	BookingKey            pgtype.Text      `db:"booking_key" json:"bookingKey"`
}

type TReserveHistory struct {
	ID             int64            `db:"id" json:"id"`
	ReserveID      int64            `db:"reserve_id" json:"reserveId"`
	HistoryAddedAt pgtype.Timestamp `db:"history_added_at" json:"historyAddedAt"`
	VmJson         string           `db:"vm_json" json:"vmJson"`
}

type TReserveOverbooking struct {
	ReserveID          int64            `db:"reserve_id" json:"reserveId"`
	BookingKey         string           `db:"booking_key" json:"bookingKey"`
	FrameDetailID      int64            `db:"frame_detail_id" json:"frameDetailId"`
	ExpirationDatetime pgtype.Timestamp `db:"expiration_datetime" json:"expirationDatetime"`
}

type TSouvenir struct {
	ReserveID  int64 `db:"reserve_id" json:"reserveId"`
	Souvenir01 int32 `db:"souvenir01" json:"souvenir01"`
	Souvenir02 int32 `db:"souvenir02" json:"souvenir02"`
	Souvenir03 int32 `db:"souvenir03" json:"souvenir03"`
	Souvenir04 int32 `db:"souvenir04" json:"souvenir04"`
	Souvenir05 int32 `db:"souvenir05" json:"souvenir05"`
}
